# Generated by Django 4.2.14 on 2024-07-28 02:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('cli_id', models.AutoField(primary_key=True, serialize=False)),
                ('cli_document', models.CharField(max_length=20, unique=True)),
                ('cli_name', models.CharField(max_length=100)),
                ('cli_address', models.CharField(max_length=255)),
                ('cli_phone', models.CharField(max_length=15)),
                ('cli_email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('pro_id', models.AutoField(primary_key=True, serialize=False)),
                ('pro_code', models.CharField(max_length=20, unique=True)),
                ('pro_name', models.CharField(max_length=100)),
                ('pro_sale_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pro_iva_percentage', models.DecimalField(decimal_places=2, default=None, max_digits=2)),
            ],
        ),
        migrations.CreateModel(
            name='SalesInvoice',
            fields=[
                ('sin_id', models.AutoField(primary_key=True, serialize=False)),
                ('sin_created_at', models.DateTimeField(auto_now_add=True)),
                ('sin_total_sale', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sin_cli_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.client')),
            ],
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('sal_id', models.AutoField(primary_key=True, serialize=False)),
                ('sal_product_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sal_calculated_iva', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sal_pro_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.product')),
                ('sal_sin_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoice', to='sales.salesinvoice')),
            ],
        ),
    ]
