# Generated by Django 4.2.14 on 2024-07-29 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='pro_iva_percentage',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=4),
        ),
    ]
