# Generated by Django 4.2.14 on 2024-07-29 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_alter_product_pro_iva_percentage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='pro_iva_percentage',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='pro_name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
